APPLICATION_ID: mylearning-servicecomb
service_description:
  name: springboot2edge
  version: 0.0.0.1
  environment: development
cse:
  service:
    registry:
      address: https://cse.cn-south-1.myhuaweicloud.com:443
      instance:
        watch: false
  config:
    client:
      serverUri: https://cse.cn-south-1.myhuaweicloud.com:443
      refreshMode: 1
      refresh_interval: 5000
  monitor:
    client:
      serverUri: https://cse.cn-south-1.myhuaweicloud.com:443
      enabled: false
  rest:
    address: 0.0.0.0:8000
  credentials:
    accessKey: ak
    secretKey: sk
#    project: cn-south-1
#    akskCustomerCipher: default
  http:
    dispatcher:
      edge:
        default:
          enabled: true
          prefix: rest
          withVersion: false
          prefixSegmentCount: 1
  accesslog:
    enabled: true
    pattern: "%h - - %t cs-uri %s %B %D %SCB-traceId"
  uploads:
    directory: uploadtest
servicecomb.config.ignoreResolveFailure: true
servicecomb:
  codec:
    printErrorMessage: true